export const GET_CURRENCIES_ATTEMPT = 'GET_CURRENCIES_ATTEMPT';
export const GET_CURRENCIES_FAIL = 'GET_CURRENCIES_FAIL';
export const GET_CURRENCIES_SUCCESS = 'GET_CURRENCIES_SUCCESS';

export const SET_CURRENCY = 'SET_CURRENCY';