export const GET_CURRENCIES_ATTEMPT = 'GET_CURRENCIES_ATTEMPT';
export const GET_CURRENCIES_FAIL = 'GET_CURRENCIES_FAIL';
export const GET_CURRENCIES_SUCCESS = 'GET_CURRENCIES_SUCCESS';

export const SET_CURRENCY = 'SET_CURRENCY';

export const GET_CURRENCY_RATES_ATTEMPT = 'GET_CURRENCY_RATES_ATTEMPT';
export const GET_CURRENCY_RATES_FAIL = 'GET_CURRENCY_RATES_FAIL';
export const GET_CURRENCY_RATES_SUCCESS = 'GET_CURRENCY_RATES_SUCCESS';