export const GET_ITEMS_ATTEMPT = 'GET_ITEMS_ATTEMPT'
export const GET_ITEMS_FAIL = 'GET_ITEMS_FAIL'
export const GET_ITEMS_SUCCESS = 'GET_ITEMS_SUCCESS'

export const ADD_ITEM = 'ADD_ITEM';

export const ARCHIVE_ITEM = 'ARCHIVE_ITEM';
export const UNARCHIVE_ITEM = 'UNARCHIVE_ITEM';