export const GET_PRODUCTS_ATTEMPT = 'GET_PRODUCTS_ATTEMPT'
export const GET_PRODUCTS_FAIL = 'GET_PRODUCTS_FAIL'
export const GET_PRODUCTS_SUCCESS = 'GET_PRODUCTS_SUCCESS'

export const ADD_PRODUCT = 'ADD_PRODUCT';

export const ARCHIVE_PRODUCT = 'ARCHIVE_PRODUCT';
export const UNARCHIVE_PRODUCT = 'UNARCHIVE_PRODUCT';